# Generated by Django 5.2.17 on 2026-10-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
